config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.production?

  resources :alerts

  get "up" => "rails/health#show", as: :rails_health_check

  root to: redirect("alerts")
end

app/models/alert.rb
class Alert < ApplicationRecord
  enum :status, %w[ pending active completed ].index_by(&:itself), default: :pending
  enum :direction, %w[ up down ]

  validates :symbol, presence: true,
    inclusion: { in: -> { Alert.available_symbols.map { it[:value] } } }
  validates :threshold, presence: true, numericality: { greater_than: 0 }
  validates :direction, presence: true
  validates :email_address,
    format: { with: URI::MailTo::EMAIL_REGEXP },
    allow_blank: true
  validates :webhook_url,
    format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) },
    allow_blank: true

  after_commit :generate_price_threshold
  after_commit :send_notification

  scope :ordered, -> { order(id: :desc) }

  broadcasts_to ->(alert) { [ "alerts" ] }, inserts_by: :prepend

  cattr_reader :available_symbols do
    file_path = Rails.root.join("lib", "available_symbols.json")
    JSON.load_file(file_path, symbolize_names: true)
  end

  private
    def generate_price_threshold
      GeneratePriceThresholdJob.perform_later(self) if pending?
    end

    def send_notification
      if saved_change_to_status? && status == "completed"
        AlertDelivery.with(alert: self).triggered.deliver_now
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: %i[ show edit update destroy ]

  # GET /alerts or /alerts.json
  def index
    @alerts = Alert.ordered
  end

  # GET /alerts/1 or /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts or /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to alerts_path, notice: "Alert was successfully created." }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1 or /alerts/1.json
  def update
    @alert.status = "pending"

    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: "Alert was successfully updated." }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1 or /alerts/1.json
  def destroy
    @alert.destroy!

    respond_to do |format|
      format.html { redirect_to alerts_path, status: :see_other, notice: "Alert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alert_params
      params.expect(alert: [ :symbol, :threshold, :direction, :email_address, :webhook_url ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  if Rails.env.production?
    http_basic_authenticate_with(
      name: Rails.application.credentials[:basic_auth_user],
      password: Rails.application.credentials[:basic_auth_password]
    )
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alerts/_alert.html.erb
<%= turbo_frame_tag alert do %>
  <div class="alert">
    <p>
      <strong>Symbol:</strong>
      <%= alert.symbol %>
    </p>

    <p>
      <strong>Threshold:</strong>
      <%= alert.threshold %>

      <% if alert.active? %>(<%= alert.price_threshold %>)<% end %>
    </p>

    <p>
      <strong>Direction:</strong>
      <%= alert.direction %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= alert.status %>
    </p>

    <div style="display: flex;">
      <div>
        <%= link_to "Edit this alert", edit_alert_path(alert) %> |
      </div>
      <div>
        <%= button_to "Delete", alert_path(alert), method: :delete %>
      </div>
    </div>

  </div>
<% end %>

app/views/alerts/_form.html.erb
<%= form_with(model: alert) do |form| %>
  <% if alert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% alert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.combobox :symbol, Alert.available_symbols %>
  </div>

  <div>
    <%= form.label :threshold, style: "display: block" %>
    <%= form.number_field :threshold, step: 0.000001 %>
  </div>

  <div>
    <%= form.label :direction, style: "display: block" %>

    <div style="display: flex;">
      <div>
        <%= form.radio_button :direction, "up" %>
        <%= form.label :direction, "up" %>
      </div>

      <div>
        <%= form.radio_button :direction, "down" %>
        <%= form.label :direction, "down" %>
      </div>
    </div>
  </div>
  
  <h2>Notifications</h2>

  <div>
    <%= form.label :email_address, style: "display: block" %>
    <%= form.email_field :email_address %>
  </div>

  <div>
    <%= form.label :webhook_url, style: "display: block" %>
    <%= form.url_field :webhook_url %>
  </div>

  <div style="margin: 20px 0;">
    <%= form.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<% content_for :title, "Editing alert" %>


<%= turbo_frame_tag @alert do %>
  <h1>Editing alert</h1>
  <%= render "form", alert: @alert %>
<% end %>

app/views/alerts/index.html.erb
<%= turbo_stream_from "alerts" %>

<p style="color: green"><%= notice %></p>

<% content_for :title, "Alerts" %>

<div style="display: flex; align-items: center">
  <h1 style="margin: 0 10px 0 0;">Alerts</h1>
  <%= link_to "New alert", new_alert_path, data: { turbo_frame: dom_id(Alert.new) } %>
</div>

<%= turbo_frame_tag Alert.new %>

<%= turbo_frame_tag "alerts" do %>
  <%= render @alerts %>
<% end %>

app/views/alerts/new.html.erb
<% content_for :title, "New alert" %>

<%= turbo_frame_tag Alert.new do %>
  <div style="border: 1px solid #ccc; padding 10px;">

    <h1>New alert</h1>

    <%= render "form", alert: @alert %>

    <br>

    <div>
      <%= link_to "Back to alerts", alerts_path %>
    </div>
  </div>
<% end %>

app/views/alerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @alert %>

<div>
  <%= link_to "Edit this alert", edit_alert_path(@alert) %> |
  <%= link_to "Back to alerts", alerts_path %>

  <%= button_to "Destroy this alert", @alert, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crypto Alert Service" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= combobox_style_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>